insert into AbstractUser (email, password, role) values ('admin@admin', 'admin', 'ADMIN')
insert into AbstractUser (email, password, role) values ('user@user', 'user', 'USER')
insert into AbstractUser (email, password, role) values ('manager@manager', 'manager', 'MANAGER')
insert into User (first_name, phoneNumber, second_name, id) values ('user', 1234567890, 'user senior', 2)
insert into Restaurant (address, information, name, id) values ('restaurace', 'restaurace', 'restaurace', 3)